### ISSUE TITLE
bug: path error

### ISSUE THREAD

**Issue by ltdrdata** [jmkl/ComfyUI-ricing#1]
https://github.com/jmkl/ComfyUI-ricing/blob/c2b5e23e612be0fa1fa494825063a600c6d2e94a/__init__.py#L12

this should be
```
	return sha256sum(os.path.join(os.path.dirname(__file__), 'user.css'))!=sha256sum(os.path.join(js_path,'user.css'))
```

**Comment by jmkl** [comment]
thanks dr. i ll patch it
